# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# jai
name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - run: npm install -g mocha
    - run: npm install
#     - run: npm run test

    - name: zip creation
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'app.zip'
        directory: app/
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - run: ls
    - run: pwd
  
    - name: 'Task 1: Connect to AWS '

      uses: aws-actions/configure-aws-credentials@v1

      with:

        aws-access-key-id: ${{ secrets.ACCESSID }}

        aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}

        aws-region: ap-south-1

        

    - name: 'Task 2: Upload  to S3 bucket'
      run: aws s3 cp app.zip s3://nodejs1234
   
   
 
